const images = {
  rotterdamBridge: require('../assets/rotterdam-bridge.jpg'),
  suspensionBridge: require('../assets/suspension-bridge.jpg'),
  ohashiBridge: require('../assets/ohashibridge.jpg'),
  bridgeDiagram1: require('../assets/bridge-diagram-1.png'),
  bridgeDiagram2: require('../assets/bridge-diagram-2.png'),
  goldenGateBridge: require('../assets/golden-gate-bridge.jpg'),
  helixBridge: require('../assets/helix-bridge.jpg'),
  highTrestleBridge: require('../assets/high-trestle.jpg'),
  brooklynBridge: require('../assets/brooklyn-bridge.jpg'),
  congestion: require('../assets/crowded.jpg'),
  bridgeJump: require('../assets/bridge-jump.jpg'),
  snoopy: require('../assets/snoopy.png'),
  threads: require('../assets/threads.png'),
  nativeThreads: require('../assets/native-threads.png'),
  rnArchitecture1: require('../assets/rn-architecture1.png'),
  rnArchitecture2: require('../assets/rn-architecture2.png'),
  rnArchitecture3: require('../assets/rn-architecture3.png'),
  peggy: require('../assets/peggy.jpg'),
  rncb: require('../assets/rncb.gif'),
  rncbSample: require('../assets/rncb-sample.png'),
  rncbSample2: require('../assets/rncb-sample2.png'),
  module1: require('../assets/module1.png'),
  module2: require('../assets/module2.png'),
  module3: require('../assets/module3.png'),
  uiComponent1: require('../assets/ui-component1.png'),
  uiComponent2: require('../assets/ui-component2.png'),
  uiComponent3: require('../assets/ui-component3.png'),
  uiComponent4: require('../assets/ui-component4.png'),
  brokenBridge: require('../assets/broken-bridge.jpg'),
  mls: require('../assets/mls-logo.svg'),
  twitterWhite: require('../assets/twitter-white.svg'),
  github: require('../assets/github.svg'),
  medium: require('../assets/medium.svg'),
};

export default images;
