const images = {
  rotterdamBridge: require('../assets/rotterdam-bridge.jpg'),
  suspensionBridge: require('../assets/suspension-bridge.jpg'),
  ohashiBridge: require('../assets/ohashibridge.jpg'),
  bridgeDiagram1: require('../assets/bridge-diagram-1.png'),
  bridgeDiagram2: require('../assets/bridge-diagram-2.png'),
  goldenGateBridge: require('../assets/golden-gate-bridge.jpg'),
  helixBridge: require('../assets/helix-bridge.jpg'),
  highTrestleBridge: require('../assets/high-trestle.jpg'),
  brooklynBridge: require('../assets/brooklyn-bridge.jpg'),
  congestion: require('../assets/crowded.jpg'),
  bridgeJump: require('../assets/bridge-jump.jpg'),
  snoopy: require('../assets/snoopy.png'),
  threads: require('../assets/threads.png'),
  nativeThreads: require('../assets/native-threads.png'),
  rnArchitecture1: require('../assets/rn-architecture-1.png'),
  rnArchitecture2: require('../assets/rn-architecture-2.png'),
  rnArchitecture3: require('../assets/rn-architecture-3.png'),
  peggy: require('../assets/peggy.jpg'),
  mls: require('../assets/mls-logo.svg'),
  twitterWhite: require('../assets/twitter-white.svg'),
  github: require('../assets/github.svg'),
  medium: require('../assets/medium.svg'),
};

export default images;
